version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://admin:qUbgMAAMvQ7Pg3uz@ac-gnv8j3r-shard-00-00.zg8wt1z.mongodb.net:27017,ac-gnv8j3r-shard-00-01.zg8wt1z.mongodb.net:27017,ac-gnv8j3r-shard-00-02.zg8wt1z.mongodb.net:27017/?ssl=true&replicaSet=atlas-rdnc2m-shard-0&authSource=admin&retryWrites=true&w=majority
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
